### ISSUE TITLE
Emptying quickly

### ISSUE THREAD

**Issue by treeowl** [fumieval/witherable#57]
`filter (const False)` can often be implemented very efficiently. Should we add a method for it? For lists, for example, `emptyOut _ = []`, and for maps, `emptyOut _ = empty`. Rewrite rules can help for some things (like maps and sequences), but they're invalid for non-strict structures like lists.

**Comment by alexfmpe** [comment]
I've also wanted this kind of thing before - this is what I came up with:

`filter (const False)` is not necessarily unique even though it is 'terminal' in a sense due to the law for `filter`:

```haskell
filter f . filter g ≡ filter (liftA2' (&&) f g)
filter f . filter (const False) ≡ filter (liftA2' (&&) f (const False))
filter f . filter (const False) ≡ filter (const False)
```

Given some `Filterable f`, consider the (completely made up for argument's sake) type:
```haskell
data MadeUp x a = MadeUp x (f a)
filter g (MadeUp x fa) = MadeUp x (filter g a) -- only possible implementation
```
In the case of `MadeUp Bool`, we have 2 elements that would satisfy the law, so `emptyOut` cannot be a constant method.

I think what would make sense, is to add the method you mentioned, and also add a new typeclass for the case where `filter (const False)` actually is unique. 
Example:

```haskell
class Filterable where
  (...)
  drain :: f a -> f a
  drain = filter (const False)

class Filterable f => Drainable f where
  drained :: f a 

instance Drainable [] where
  drained = []
```

**Comment by treeowl** [comment]
@alexfmpe, surely

```haskell
drain :: f a -> f b
```

**Comment by alexfmpe** [comment]
Oooh right.
We have `filter :: (a -> Bool) -> f a -> f a`, so `drain = filter (const False)` wouldn't work.
However, `mapMaybe :: (a -> Maybe b) -> f a -> f b` so `drain = mapMaybe (const Nothing)` would fit the bill.

**Comment by treeowl** [comment]
Yes, exactly. I should've phrased it that way to begin with.

**Comment by treeowl** [comment]
There are situations where the monomorphic version can be written more efficiently than the polymorphic one, because the polymorphic one may have to build a new copy of the same structure just to satisfy the type checker. I don't know that it's worth adding an extra method for that.

**Comment by fumieval** [comment]
I admit I'm not sure what the usecase is. It may be useful when there's a retained value (e.g. `Const`), but that's also kinda trivial...

**Comment by Ericson2314** [comment]
It is also an identity for Align, I'd think.

**Comment by jcranch** [comment]
(Thanks for the pointer, @phadej)

@fumieval I have a use case for you. In my [generic map merging library](https://github.com/jcranch/ModernMapMerge), a `WhenMissing` merge tactic is implemented as "anything that can act on a `Witherable`", and the `dropMissing` tactic is precisely `drain`.

Since one wants `dropMissing` to be implemented rapidly on real-life data structures, having a specialised `drain` method is desirable.
