### ISSUE TITLE
Witherable is (Traversable, Filterable), not something more specific

### ISSUE THREAD

**Issue by gereeter** [fumieval/witherable#63]
The following is law-abiding and (as far as I can tell, necessarily according to the laws) matches all existing instances:

```haskell
instance (Traversable t, Filterable t) => Witherable t where
    wither f = fmap catMaybes . traverse f
```

There isn't a need for a separate type class. Instead, `wither` could just be a constrained default-defined method of `Filterable` as in

```haskell
class Filterable t where
    -- | Laws:
    -- prop> filter (const True) == id
    -- prop> filter f . filter g == filter (\x -> g x && f x)
    filter :: (a -> Bool) -> t a -> t a

    catMaybes :: Functor t => t (Maybe a) -> t a
    catMaybes = fmap fromJust . filter isJust

    mapMaybe :: Functor t => (a -> Maybe b) -> t a -> t b
    mapMaybe f = catMaybes . fmap f

    wither :: Traversable t => (a -> f (Maybe b)) -> t a -> f (t b)
    wither f = fmap catMaybes . traverse f
```

(`Functor` isn't necessary for `Filterable` to make sense, either: `Set` could implement it just fine, for example.) Is there any reason for the separation besides history and backwards compatibility? With an appropriate type class synonym or just a blanket `Witherable` implementation like the one above, the only code needing to change would be custom implementations.

**Comment by treeowl** [comment]
Constrained methods are often trouble, and that's certainly the case here. Writing an instance for something *not* `Traversable` will require `undefined`.

**Comment by gereeter** [comment]
> Writing an instance for something not `Traversable` will require `undefined`.

No? The default definition still works. It isn't rejected just because it has an unsatisfiable bound, and its reference to `traverse` is just a selector on the (never-inhabited) passed-in Traversable dictionary.

**Comment by treeowl** [comment]
Ah, interesting. I didn't realize that would work. So what's the actual *advantage* of the collapse you propose?

**Comment by gereeter** [comment]
> So what's the actual *advantage* of the collapse you propose?

It isn't large and there are downsides; I intended this issue as a documentation request and question first and as a suggestion second. This fact didn't seem to be mentioned anywhere besides the lack of required methods on `Witherable`, and I didn't see any evidence of it being considered. That said:

- There are contexts where you get `Traversable` and `Filterable` bounds separately and need to use `wither`. I personally hit this issue when trying to build a lens hierarchy that worked well with filtering/deletion. This is rare, though, and generally possible to work around (which I did).
- With a single core class, there are fewer things to think about. Filtering is a simple concept that almost all functional programmers will be used to, and having a single class `Filterable` which just means "containers that can be filtered" avoids adding new concepts. It isn't intuitive why filtering would imply a `Functor` constraint, and withers are not standard terminology. This also ties into the weakest argument of the bunch, which is aesthetics.
- Monomorphic containers don't implement `Functor` and need that constraint dropped to fit into the library.

There are definitely downsides, and the biggest I know of is that when you have
```haskell
data Wrapper t a
instance Traversable t => Traversable (Wrapper t)
```
you can't prove to the compiler that `Traversable (Wrapper t)` implies `Traversable t` (generally), so the `wither` implementation of `Wrapper t` can't use `wither` on `t`.

**Comment by fumieval** [comment]
It seems like we could say that it's just because of historical reasons, however there are few classes with constrained methods (none in base?). I wonder if I'm missing some reason to avoid constrained methods.

**Comment by alexfmpe** [comment]
If a method in class A has a constraint for class B, it could equally be in class B with a constraint for class A, no?
It feels like such a signature really belongs outside both classes, but the implementation can't be overridden for more specific instantiations unless it's inside a class.

**Comment by leifmetcalf** [comment]
There are classes with constrained methods in base, notably [Data.Foldable.Foldable](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Foldable.html#v:foldMap).

**Comment by fumieval** [comment]
I tried adding `witherRep` to `Filterable` as an experiment. Turns out that it (or constrained methods in general) prevents GeneralisedNewtypeDeriving. Not much worse than the status quo (Witherable can't be GND'd either), but given the increasing use of GND and DerivingVia, adding constrained methods seems undesiable.

```haskell
  witherRep :: (Traversable f, Applicative m) => (f b -> r) -> (a -> m (Maybe b)) -> t a -> m r
  witherRep p f = fmap (p . catMaybes) . traverse
```

**Comment by phadej** [comment]
> (Functor isn't necessary for Filterable to make sense, either: Set could implement it just fine,

Not true. `mapMaybe @Set :: (a -> Maybe b) -> Set a -> Set b` will require `Ord b`. (It wouldn't only for monotonic predicates).

**Comment by viercc** [comment]
`Witherable t` is not just `(Filterable t, Traversable t)`. The following is law-abiding `Filterable` instance:

```haskell
newtype Wicked a = W [a]
  deriving (Functor, Foldable, Traversable)

instance Filterable Wicked where
  -- mapMaybe f (W [a1,a2,...]) = W [b1, b2, ...]
  -- if all of [f a1, f a2, ...] are Just. Otherwise, it returns (W []).
  mapMaybe f = fromMaybe (W []) . traverse f
```

With this instance, the following `wither'` doesn't satisfy the *composition* law.

```haskell
wither' :: Applicative f => (a -> f (Maybe b)) -> Wicked a -> f (Wicked b)
wither' f = fmap catMaybes . traverse f

onlyEven :: Int -> Maybe Int
onlyEven n = if even n then Just n else Nothing

e1, e2 :: W Int -> Compose Identity IO (W ())
e1 = Compose . fmap (wither (fmap Just . print)) . wither (Identity . onlyEven)
e2 = wither (Compose . fmap (wither (fmap Just . print)) . Identity . onlyEven) 
```

From the composition law  `e1` and `e2` should be equal, but by running IO action
inside them, `e1 (W [0,1])` prints out nothing while `e2 (W [0,1])` prints out 0.

If I haven't mistaken, `wither f = fmap catMaybes . traverse f` follows from witherable laws plus one additional law:

```haskell
-- @mapMaybe@ is a special case of @wither@
wither (Identity . f) = Identity . mapMaybe f
```

So there can't be a lawful `wither` which generalizes `mapMaybe` for `Wicked`.

**Comment by phadej** [comment]
@viercc nice. I made https://github.com/fumieval/witherable/pull/80 to document that example.

Either `Filterable` laws are too lax or `Witherable` laws are too strict. (IMO `Wicked` is morally incorrect `Filterable`, but current laws hold, so it's good).

**Comment by phadej** [comment]
Note: If I modify the composition test to ignore which effect happened:

```diff
-        run :: Compose (State S) (State S) b -> ((b, S), S)
-        run m = first (\x -> runState x s1) (runState (getCompose m) s0)
+        run :: Compose (State S) (State S) b -> b
+        run m = fst $ fst $ first (\x -> runState x s1) (runState (getCompose m) s0)
```

the test-suite in #80 will pass. - this is what I refer as `Witherable` laws are maybe too strict.

**Comment by alexfmpe** [comment]
> Either Filterable laws are too lax or Witherable laws are too strict. (IMO Wicked is morally incorrect Filterable, but current laws hold, so it's good).

How about a law that requires that elements be filtered out only if they fail the predicate themselves, rather than thrown out as a consequence of others being filtered: `filter f . filter g $ xs = filter g xs <=> (forall x. g x => f x) \/ (filter f xs = xs))`
Read: if `filter f` doesn't throw anything out that `filter g` didn't, then either `f` represents a superset of `g`, or `filter f` wouldn't throw anything out in the first place.

In the case of `Wicked [1,2]`, both `filter odd` and `filter even` would result in `Wicked []`, but this law wouldn't hold since neither `odd x => even x` nor `even x => odd x` and both of them would throw out elements
Another example is `Data.Tree` - if a parent is filtered out (e.g. the root), there's nowhere to put the children and preserve the shape.

**Comment by phadej** [comment]
I get an idea, but I'm missing something:

```
f = \_ -> False
g = \x -> case x of 1 -> False; _ -> True
xs = [1]

filter f (filter g [1]) = []
filter g [1]            = []

filter f [1] /= [1]
g 0 =/> f 0 (True =/> False)
```

Note: we cannot say `forall x in xs. g x => f x` as that would imply something like `Foldable f => Filterable xs`. Maybe that isn't bad addition/requirement.

**Comment by alexfmpe** [comment]
> f = \_ -> False
> g = \x -> case x of 1 -> False; _ -> True
> xs = [1]
> 
> filter f (filter g [1]) = []
> filter g [1]            = []
> 
> filter f [1] /= [1]
> g 0 =/> f 0 (True =/> False)

This does not hold for all inputs though. Guess I missed a quantifier:
`forall xs. filter f . filter g $ xs = filter g xs <=> (forall x. g x => f x) \/ (filter f xs = xs))`

**Comment by alexfmpe** [comment]
> I get an idea, but I'm missing something:
> 
> ```
> f = \_ -> False
> g = \x -> case x of 1 -> False; _ -> True
> xs = [1]
> 
> filter f (filter g [1]) = []
> filter g [1]            = []
> 
> filter f [1] /= [1]
> g 0 =/> f 0 (True =/> False)
> ```

Oh right. Then how about
```
forall xs. filter f xs = filter (not . f) xs <=> forall h. xs = filter h xs
```

If it's possible for `f` and `not . f` to throw out exactly the same elements, then the input must have been 'empty' ( in the sense of #58 )

This means we can't have instances where you throw out 'extra' elements, because then `f` and `not . f` could overlap:
```
xs = W [1,2]
filter odd xs = filter even xs 
filter odd xs /= xs

**Comment by phadej** [comment]
I won't act as your secretary. Make a patch adding a test for your law.

**Comment by alexfmpe** [comment]
I didn't mean to imply you should do anything. I was basically commenting on
> Wicked is morally incorrect Filterable, but current laws hold,

**Comment by phadej** [comment]
I don't understand what

```
forall xs. filter f xs = filter (not . f) xs <=> forall h. xs = filter h xs
```

means.

```haskell
    prop_alex :: Fun A Bool -> Fun A Bool -> f A ->Property
    prop_alex f' g' xs =
        (filter f xs == filter (not . f) xs)
        ===
        (xs == filter g xs)
      where
        f = applyFun f'
        g = applyFun g'
```

doesn't pass.

Please try your ideas before proposing them! If you think you on something, but cannot make it work, say that, you'll save everyones time.

---

For now i just close this issue, there is a counterexample to *Witherable is (Traversable, Filterable)*. If someone comes up with better laws they should open a new issue.

**Comment by alexfmpe** [comment]
> I don't understand what
> forall xs. filter f xs = filter (not . f) xs <=> forall h. xs = filter h xs
> means.

If `filter f` and `filter (not . f)` end up with the same result, either the input was empty (and the predicate doesn't matter), or it was non-empty and they both threw out the same elements. But since exactly one of `f x` and `not (f x)` is false, the predicates never overlap, so if filtering with those predicates throws out the same elements, then elements for which the predicate does hold are also being thrown out, causing the overlap, as is the case for `Wicked`. *If* such overlap behavior is undesired, then a new law is needed to rule it out.

> doesn't pass.

I don't see how there can be a test on whether a law *passes*. One could check whether it rules out the instance we both felt was morally wrong, whether it rules out instances we certainly want, whether it break backwards compatibility, but that's it.
Every law will restrict the set of possible instances. Whether a specific instance matches the law doesn't determine whether the law or the instance are useful or not. It just means those two things are incompatible. It's a judgement call (up to the maintainers) which sets of laws/instances should be elevated to which classes with which names.
The law is the spec, not the implementation - you don't *make it work*, you *choose* it.

> If you think you on something, but cannot make it work, say that, you'll save everyone's time.

Again, I did not request any time investment from anyone. If you don't want to engage on discussion about what laws make sense for Filterable, then don't. If you want to test some things, then do.
I don't understand why you're doing things I didn't ask for and then complaining that I made you do them.
